site_name: YAMS
site_description: Yet Another Memory System — persistent memory for LLMs and applications.
site_url: https://trvon.github.io/yams
repo_url: https://sr.ht/~trvon/yams/
repo_name: sr.ht/~trvon/yams
docs_dir: docs
site_dir: site
use_directory_urls: true

nav:
  - Home: index.md
  - Get Started:
      - Installation: user_guide/installation.md
      - CLI: user_guide/cli.md
      - Self-hosting: hosting/self_hosting.md
      - User Guide: user_guide/README.md
      - Prompts:
          - CLI usage: PROMPT.md
          - Engineering: PROMPT-eng.md
  - Docs:
      - Guides:
          - Tutorials: user_guide/tutorials/README.md
          - Embeddings: user_guide/embeddings.md
          - MCP: user_guide/mcp.md
      - API:
          - Overview: api/README.md
          - MCP Tools: api/mcp_tools.md
      - Cloud:
          - Hosting: hosting/README.md
          - Early Access: hosting/early-access.md
          - Pricing (Preview): hosting/pricing.md
          - Services: services/README.md
          - Support Plans: services/support_plans.md
          - Contact: services/contact.md
      - Admin:
          - Configuration: admin/configuration.md
          - Performance Tuning: admin/performance_tuning.md
          - Tuning Profiles: admin/tuning_profiles.md
      - Roadmap: roadmap.md
      - Architecture:
          - Daemon and Services: architecture/daemon_architecture.md
          - Plugin and Content Extraction: architecture/plugin_architecture.md
      - Reference:
          - Developer:
              - Setup: developer/setup.md
              - Build System: developer/build_system.md
              - Contributing: developer/contributing.md
              - Architecture Notes: developer/architecture/README.md
              - Mobile Bindings: developer/mobile-bindings.md
          - Operations:
              - Deployment: pbi/operations/deployment.md
              - Monitoring: pbi/operations/monitoring.md
              - Backup: pbi/operations/backup.md
          - Build:
              - GCC Build: BUILD-GCC.md
          - Plugins: PLUGINS.md
          - Testing:
              - Coverage Report: testing/coverage_report.md
          - Benchmarks: benchmarks/performance_report.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - content.code.copy
  palette:
    scheme: slate
  language: en
  font:
    text: "JetBrains Mono"
    code: "JetBrains Mono"
  logo: assets/yams.png
  favicon: assets/yams.png

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta
  - sane_lists
  - smarty
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search

extra:
  social:
    - icon: simple/sourcehut
      link: https://sr.ht/~trvon/yams/
      name: SourceHut
    - icon: fontawesome/brands/github
      link: https://github.com/trvon/yams
      name: GitHub (mirror)
    - icon: fontawesome/solid/envelope
      link: mailto:support@yamsmemory.ai
      name: Email
  announcement: '<a href="/hosting/early-access/">Join Hosting Early Access →</a>'

extra_css:
  - assets/retro.css
  - assets/landing.css
extra_javascript:
  - assets/landing.js
copyright: "© YAMS"
